PWDTD_P8/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from minerals import views

urlpatterns = [
    url(r'^minerals/', include('minerals.urls', namespace='minerals')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home)
]

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ]

minerals/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'(?P<pk>\d+)', views.one_mineral, name='see_mineral'),
    url(r'search/.*', views.search, name='search'),
    url(r'random', views.random_mineral, name='random_mineral'),
    url(r'starts_with/(?P<start_letter>\w)', views.first_letter, name='first_letter'),
    url(r'^$', views.home, name='home'),
    url(r'group/(?P<grouping>\w+)', views.group_minerals, name='groups'),
    url(r'streak/(?P<streak_color>\w+)', views.streak_minerals, name='streaks')
]

minerals/models.py
from django.db import models

# Create your models here.


class Mineral(models.Model):
    name = models.CharField(max_length=100)
    image_filename = models.CharField(max_length=255, blank=True)
    image_caption = models.CharField(max_length=255, blank=True)
    category = models.CharField(max_length=255, blank=True)
    formula = models.CharField(max_length=255, blank=True)
    strunz_classification = models.CharField(max_length=255, blank=True)
    crystal_system = models.CharField(max_length=255, blank=True)
    unit_cell = models.CharField(max_length=255, blank=True)
    color = models.CharField(max_length=255, blank=True)
    crystal_symmetry = models.CharField(max_length=255, blank=True)
    cleavage = models.CharField(max_length=255, blank=True)
    mohs_scale_hardness = models.CharField(max_length=255, blank=True)
    luster = models.CharField(max_length=255, blank=True)
    streak = models.CharField(max_length=255, blank=True)
    diaphaneity = models.CharField(max_length=255, blank=True)
    optical_properties = models.CharField(max_length=255, blank=True)
    refractive_index = models.CharField(max_length=255, blank=True)
    crystal_habit = models.CharField(max_length=255, blank=True)
    specific_gravity = models.CharField(max_length=255, blank=True)
    group = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ['name',]

    def __str__(self):
        return self.name

minerals/views.py
from django.shortcuts import render, HttpResponseRedirect, Http404, reverse
from django.contrib import messages


import random

from . import models


def home(request):
    return HttpResponseRedirect(
        reverse(
            'minerals:first_letter',
            kwargs={'start_letter': 'A'}
        )
    )


def one_mineral(request, pk):
    try:
        show_mineral = models.Mineral.objects.values().get(pk=pk)
        basis_name = show_mineral['name']
        try:
            next_mineral = models.Mineral.objects.order_by('name').filter(name__gt=basis_name)[0]
        except IndexError:
            next_mineral = models.Mineral.objects.order_by('name').all()[0]
        try:
            previous_mineral = models.Mineral.objects.order_by('name').filter(name__lt=basis_name)[0]
        except IndexError:
            previous_mineral = models.Mineral.objects.order_by('-name').all()[0]
    except models.Mineral.DoesNotExist:
        raise Http404('Mineral Does Not Exist')
    return render(
        request=request,
        template_name='minerals/mineral_detail.html',
        context={
            'show_mineral': show_mineral,
            'next_mineral': next_mineral.pk,
            'previous_mineral': previous_mineral.pk,
        },
    )


def random_mineral(request):
    random_number = random.randint(1, models.Mineral.objects.count())
    return HttpResponseRedirect(
        reverse(
            'minerals:see_mineral',
            kwargs={
                'pk': random_number,
            }
        )
    )


def first_letter(request, start_letter):
    first_letter_minerals = models.Mineral.objects.filter(name__startswith=start_letter).values_list('pk', 'name')
    return render(
        request=request,
        template_name='minerals/searched.html',
        context={
            'search_results': first_letter_minerals,
            'page_title': start_letter
        }
    )


def group_minerals(request, grouping):
    mineral_group = models.Mineral.objects.filter(group__icontains=grouping).values_list('pk', 'name')
    return render(
        request=request,
        template_name='minerals/searched.html',
        context={
            'search_results': mineral_group,
            'page_title': grouping,
        }
    )


def streak_minerals(request, streak_color):
    streak_color_minerals = models.Mineral.objects.filter(streak__icontains=streak_color).values_list('pk', 'name')
    return render(
        request=request,
        template_name='minerals/searched.html',
        context={
            'search_results': streak_color_minerals,
            'page_title': streak_color
        }
    )


def search(request):
    term = request.GET.get('q')
    search_results = models.Mineral.objects.filter(name__icontains=term).values_list('pk', 'name')
    if search_results:
        return render(
            request=request,
            template_name='minerals/searched.html',
            context={
                'search_results': search_results,
                'page_title': 'Search Results'
            },
        )
    else:
        messages.add_message(
            request=request,
            level=messages.INFO,
            message='Could not find anything to match your search of "{}"...'.format(term),
        )
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

minerals/templates/minerals/group_nav.html
{% for group_name in group_names %}
    <li class="minerals__item">
        <a class="minerals__anchor" href="{% url 'minerals:groups' grouping=group_name %}">{{ group_name|title }}</a>
    </li>
{% endfor %}

minerals/templates/minerals/index.html
<!DOCTYPE html>
<html lang="en">

{% load static from staticfiles %}
{% load mineral_tags %}

<head>
    <meta charset="utf-8">
    {% block title %}
        <title>Macky's Minerals | A magnificent catalog of minerals</title>
    {% endblock title %}
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'static/css/global.css' %}">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'static/js/minerals_js.js' %}"></script>
</head>
<body>
    <div class="bounds">

        <div class="grid-100">
            <a href="{% url 'minerals:home' %}">
                <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
                    <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
                    <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
                    <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
                </svg>
            <h1 class="logo__name text-centered">Macky's Minerals</h1>
            </a>
            <p class="logo__text text-centered">They're not rocks!</p>
        </div>

        <div class="grid-100">

            <div class="alpha__container">
                <ul class="alpha__list">
                    {% letters_for_nav %}
                </ul>
            </div>

        </div>

        <div class="grid-100">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
            {% endif %}

            <div class="content__container">

                <div class="grid-60 grid-push-30 mineral__container">
                    {% block main_body_content %}
                            <ul class="minerals__container">
                                {% for indexed, named in all_mineral_names %}
                                    <li class="minerals__item">
                                        <a class="minerals__anchor" href="{% url 'minerals:see_mineral' pk=indexed %}">{{ named }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                    {% endblock main_body_content %}
                </div>

                <div class="grid-25 grid-pull-60">

                    <div class="sidebar__container">

                        <form class="search__form" action="{% url 'minerals:search' %}" method="GET">
                            <input type="text" name="q">
                            <input class="search__button" type="submit" name="Search" value="Search">
                        </form>


                        <div class="circle--filter circle--secondary--module">
                            <ul class="circle--link--list">
                                <h3 class="filter__headers">Category</h3>
                                {% groups_nav %}
                            </ul>
                            <ul class="circle--link--list">
                                <h3 class="filter__headers">Streak</h3>
                                {% streak_nav %}
                            </ul>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="minerals__random">
        <a class="minerals__anchor" href="{% url 'minerals:random_mineral' %}">Show random mineral</a>
    </div>
</body>
</html>

minerals/templates/minerals/letter_nav.html
{% load mineral_tags %}

{% for letter in letters %}
    <li>
        <a class="letter__links" href="{% url 'minerals:first_letter' start_letter=letter %}" >
            {{ letter }}
        </a>
    </li>
{% endfor %}

minerals/templates/minerals/mineral_detail.html
{% extends 'minerals/index.html' %}
{% load static from staticfiles %}
{% load mineral_tags %}

{% block title %}
    <title>Macky's Minerals | {{ show_mineral.name }}</title>
{% endblock title %}
{% block main_body_content %}
    <div class="grid-100 mineral__container">
        <h1 class="mineral__name">{{ show_mineral.name }}</h1>
        <div class="mineral__image-bg">
            <img class="mineral__image" src="{% static 'images/' %}{{ show_mineral.name|title }}.jpg">
            <p class="mineral__caption">{{ show_mineral.caption }}</p>
        </div>
    </div>
    <div class="mineral__table-container">
        <table class="mineral__table">
            {% for key, value in show_mineral.items %}
                {% if value %}
                    {% if key != 'name' and key != 'image_filename' and key != 'image_caption' and key != 'id' %}
                        <tr>
                            <td class="mineral__category">{{ key|pretty_output }}</td>
                                {% if key == 'formula' %}
                                    <td class="mineral_formula">{{ value|safe }}</td>
                                {% else %}
                                    <td>{{ value }}</td>
                                {% endif %}
                        </tr>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </table>
    </div>
    <a class="previous_mineral" href="{% url 'minerals:see_mineral' pk=previous_mineral %}">Previous</a>
    <a class="next_mineral" href="{% url 'minerals:see_mineral' pk=next_mineral %}">Next</a>
{% endblock main_body_content %}

minerals/templates/minerals/searched.html
{% extends 'minerals/index.html' %}

{% block title %}
    <title>Macky's Minerals | {{ page_title|title }}</title>
{% endblock title %}

{% block main_body_content %}
    <div class="grid-100">
        <ul class="minerals__container">
            {% for indexed, named in search_results %}
                <li class="minerals__item">
                    <a class="minerals__anchor" href="{% url 'minerals:see_mineral' pk=indexed %}">{{ named }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock main_body_content %}

minerals/templates/minerals/streak_nav.html
{% for streak in streak_names %}
    <li class="minerals__item">
        <a class="streak__anchor" href="{% url 'minerals:streaks' streak_color=streak %}">{{ streak|title }}</a>
    </li>
{% endfor %}